# Generated by Django 2.0.6 on 2021-10-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20211004_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', editable=False, max_length=255, unique=True),
        ),
    ]
