# Generated by Django 2.0.6 on 2021-10-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_auto_20211004_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Category', verbose_name='カテゴリ'),
        ),
    ]
