# Generated by Django 2.0.6 on 2021-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_auto_20211004_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
